services:
  - type: web
    name: amex-tracker
    runtime: static
    buildCommand: cd tracker && npm install && npm run build
    staticPublishPath: tracker/dist
    pullRequestPreviewsEnabled: false
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
